"""Initial Schema with Carbon Models

Revision ID: 6cafe46a3428
Revises: 
Create Date: 2026-03-06 19:02:35.960295

"""
import warnings
from typing import TYPE_CHECKING

import sqlalchemy as sa
from alembic import op
from advanced_alchemy.types import EncryptedString, EncryptedText, FernetBackend, GUID, ORA_JSONB, DateTimeUTC, StoredObject, PasswordHash
from sqlalchemy import Text  # pyright: ignore  # noqa: F401
from sqlalchemy.dialects import postgresql
if TYPE_CHECKING:
    from collections.abc import Sequence  # pyright: ignore

__all__ = ("downgrade", "upgrade", "schema_upgrades", "schema_downgrades", "data_upgrades", "data_downgrades")

sa.GUID = GUID # pyright: ignore
sa.DateTimeUTC = DateTimeUTC  # pyright: ignore
sa.ORA_JSONB = ORA_JSONB  # pyright: ignore
sa.EncryptedString = EncryptedString  # pyright: ignore
sa.EncryptedText = EncryptedText  # pyright: ignore
sa.StoredObject = StoredObject  # pyright: ignore
sa.PasswordHash = PasswordHash  # pyright: ignore

# revision identifiers, used by Alembic.
revision = '6cafe46a3428'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            schema_upgrades()
            data_upgrades()

def downgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            data_downgrades()
            schema_downgrades()

def schema_upgrades() -> None:
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dataapp_apiresultkeymapping',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('key_name', sa.String(length=30), nullable=True),
    sa.Column('cn_name', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dataapp_apiresultkeymapping'))
    )
    op.create_table('dataapp_emissionfactor',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('scope', sa.String(length=10), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('sub_category', sa.String(length=64), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('factor_value', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('factor_unit', sa.String(length=32), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=128), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dataapp_emissionfactor'))
    )
    op.create_table('dataapp_employeecommute',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('name', sa.String(length=10), nullable=False),
    sa.Column('category', sa.String(length=10), nullable=True),
    sa.Column('car_power_type', sa.Integer(), nullable=True),
    sa.Column('mileage', sa.Float(), nullable=True),
    sa.Column('unit_consumption', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dataapp_employeecommute'))
    )
    op.create_table('dataapp_energystoragevalue',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('cn_total', sa.Float(), nullable=True),
    sa.Column('ratio_total', sa.Float(), nullable=True),
    sa.Column('cn1', sa.Float(), nullable=True),
    sa.Column('ratio1', sa.Float(), nullable=True),
    sa.Column('cn2', sa.Float(), nullable=True),
    sa.Column('ratio2', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dataapp_energystoragevalue'))
    )
    op.create_table('dataapp_enterpriseinfo',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('belong_unit', sa.String(length=100), nullable=True),
    sa.Column('people_count', sa.Integer(), nullable=True),
    sa.Column('park_area', sa.Float(), nullable=True),
    sa.Column('unify_code', sa.String(length=30), nullable=True),
    sa.Column('industry', sa.String(length=30), nullable=True),
    sa.Column('store_area', sa.Float(), nullable=True),
    sa.Column('green_area', sa.Float(), nullable=True),
    sa.Column('location', sa.String(length=50), nullable=True),
    sa.Column('other_info', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'cockroachdb').with_variant(sa.ORA_JSONB(), 'oracle').with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True, comment='其他信息'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dataapp_enterpriseinfo'))
    )
    op.create_table('dataapp_inmoney',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('rkdbh', sa.String(length=20), nullable=False),
    sa.Column('gysmc', sa.String(length=100), nullable=True),
    sa.Column('gysbm', sa.String(length=15), nullable=True),
    sa.Column('rkrq', sa.String(length=30), nullable=True),
    sa.Column('wlbh', sa.String(length=15), nullable=True),
    sa.Column('wlms', sa.String(length=300), nullable=True),
    sa.Column('pc', sa.String(length=15), nullable=True),
    sa.Column('jldw', sa.String(length=10), nullable=True),
    sa.Column('shsl', sa.Float(), nullable=True),
    sa.Column('shdj', sa.Float(), nullable=True),
    sa.Column('shje', sa.Float(), nullable=True),
    sa.Column('ckmc', sa.String(length=50), nullable=True),
    sa.Column('add_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dataapp_inmoney'))
    )
    op.create_table('dataapp_iottelemetry',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('site_id', sa.String(length=64), nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=False),
    sa.Column('ts', sa.Integer(), nullable=False),
    sa.Column('reading_time', sa.DateTime(), nullable=False),
    sa.Column('active_power', sa.Float(), nullable=True),
    sa.Column('reactive_power', sa.Float(), nullable=True),
    sa.Column('voltage_a', sa.Float(), nullable=True),
    sa.Column('current_a', sa.Float(), nullable=True),
    sa.Column('total_energy', sa.Float(), nullable=True),
    sa.Column('interval', sa.String(length=8), nullable=False),
    sa.Column('raw_payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'cockroachdb').with_variant(sa.ORA_JSONB(), 'oracle').with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True, comment='原始 JSON 报文'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dataapp_iottelemetry'))
    )
    with op.batch_alter_table('dataapp_iottelemetry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dataapp_iottelemetry_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dataapp_iottelemetry_reading_time'), ['reading_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_dataapp_iottelemetry_site_id'), ['site_id'], unique=False)

    op.create_table('dataapp_monitorsector',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('area', sa.String(length=30), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('area_id', sa.Integer(), nullable=True),
    sa.Column('is_enable', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dataapp_monitorsector')),
    sa.UniqueConstraint('code', name=op.f('uq_dataapp_monitorsector_code'))
    )
    op.create_table('dataapp_outmoney',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('ckdbh', sa.String(length=20), nullable=False),
    sa.Column('xmmc', sa.String(length=200), nullable=True),
    sa.Column('xmdy', sa.String(length=15), nullable=True),
    sa.Column('wlbm', sa.String(length=15), nullable=True),
    sa.Column('wlms', sa.String(length=300), nullable=True),
    sa.Column('pc', sa.String(length=15), nullable=True),
    sa.Column('jldw', sa.String(length=10), nullable=True),
    sa.Column('sfsl', sa.Float(), nullable=True),
    sa.Column('dj', sa.Float(), nullable=True),
    sa.Column('je', sa.Float(), nullable=True),
    sa.Column('gzrq', sa.String(length=30), nullable=True),
    sa.Column('gysmc', sa.String(length=100), nullable=True),
    sa.Column('gc', sa.String(length=100), nullable=True),
    sa.Column('lldh', sa.String(length=15), nullable=True),
    sa.Column('ckdd', sa.String(length=100), nullable=True),
    sa.Column('add_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dataapp_outmoney'))
    )
    op.create_table('dataapp_videomonitor',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('f_area', sa.String(length=50), nullable=True),
    sa.Column('f_area_type', sa.String(length=10), nullable=True),
    sa.Column('video_url', sa.String(length=200), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(length=20), nullable=True),
    sa.Column('install_height', sa.Float(), nullable=True),
    sa.Column('install_method', sa.String(length=20), nullable=True),
    sa.Column('vedio_type', sa.String(length=20), nullable=True),
    sa.Column('pixel', sa.String(length=10), nullable=True),
    sa.Column('brand', sa.String(length=20), nullable=True),
    sa.Column('b_model', sa.String(length=30), nullable=True),
    sa.Column('install_time', sa.String(length=30), nullable=True),
    sa.Column('install_x', sa.Float(), nullable=True),
    sa.Column('install_y', sa.Float(), nullable=True),
    sa.Column('add_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dataapp_videomonitor'))
    )
    op.create_table('role',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_role')),
    sa.UniqueConstraint('name', name=op.f('uq_role_name')),
    sa.UniqueConstraint('slug', name='uq_role_slug')
    )
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.create_index('ix_role_slug_unique', ['slug'], unique=True)

    op.create_table('tag',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tag')),
    sa.UniqueConstraint('slug', name='uq_tag_slug')
    )
    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.create_index('ix_tag_slug_unique', ['slug'], unique=True)

    op.create_table('team',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_team')),
    sa.UniqueConstraint('slug', name='uq_team_slug')
    )
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_team_name'), ['name'], unique=False)
        batch_op.create_index('ix_team_slug_unique', ['slug'], unique=True)

    op.create_table('user_account',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('username', sa.String(length=30), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('verified_at', sa.Date(), nullable=True),
    sa.Column('joined_at', sa.Date(), nullable=False),
    sa.Column('login_count', sa.Integer(), nullable=False),
    sa.Column('password_reset_at', sa.DateTimeUTC(timezone=True), nullable=True),
    sa.Column('failed_reset_attempts', sa.Integer(), nullable=False),
    sa.Column('reset_locked_until', sa.DateTimeUTC(timezone=True), nullable=True),
    sa.Column('totp_secret', sa.EncryptedString(key='136137cf918eac1dc8da4472c803a3481987a420d063c6278c053253cc225eab', backend=FernetBackend, length=None), nullable=True),
    sa.Column('is_two_factor_enabled', sa.Boolean(), nullable=False),
    sa.Column('two_factor_confirmed_at', sa.DateTimeUTC(timezone=True), nullable=True),
    sa.Column('backup_codes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_account')),
    comment='User accounts for application access'
    )
    with op.batch_alter_table('user_account', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_account_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_account_username'), ['username'], unique=True)

    op.create_table('audit_log',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('actor_id', sa.GUID(length=16), nullable=True),
    sa.Column('actor_email', sa.String(length=255), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=True),
    sa.Column('target_id', sa.String(length=36), nullable=True),
    sa.Column('target_label', sa.String(length=255), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['user_account.id'], name=op.f('fk_audit_log_actor_id_user_account'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log')),
    comment='Audit trail for system events and admin actions'
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_target_id'), ['target_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_target_type'), ['target_type'], unique=False)

    op.create_table('dataapp_carbonauditlog',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('record_type', sa.String(length=64), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=16), nullable=False),
    sa.Column('operator_id', sa.GUID(length=16), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['operator_id'], ['user_account.id'], name=op.f('fk_dataapp_carbonauditlog_operator_id_user_account'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dataapp_carbonauditlog'))
    )
    with op.batch_alter_table('dataapp_carbonauditlog', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dataapp_carbonauditlog_operator_id'), ['operator_id'], unique=False)

    op.create_table('dataapp_monitorequipment',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.Column('code2', sa.String(length=30), nullable=True),
    sa.Column('sector_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('category', sa.Integer(), nullable=True),
    sa.Column('supplier', sa.String(length=20), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('trip_state', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=50), nullable=True),
    sa.Column('install_time', sa.DateTime(), nullable=True),
    sa.Column('sort_index', sa.Integer(), nullable=True),
    sa.Column('is_enable', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['sector_id'], ['dataapp_monitorsector.id'], name=op.f('fk_dataapp_monitorequipment_sector_id_dataapp_monitorsector'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dataapp_monitorequipment'))
    )
    with op.batch_alter_table('dataapp_monitorequipment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dataapp_monitorequipment_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_dataapp_monitorequipment_sector_id'), ['sector_id'], unique=False)

    op.create_table('dataapp_monitorsectorphoto',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('path', sa.String(length=255), nullable=True),
    sa.Column('sector_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('area_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sector_id'], ['dataapp_monitorsector.id'], name=op.f('fk_dataapp_monitorsectorphoto_sector_id_dataapp_monitorsector'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dataapp_monitorsectorphoto'))
    )
    with op.batch_alter_table('dataapp_monitorsectorphoto', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dataapp_monitorsectorphoto_sector_id'), ['sector_id'], unique=False)

    op.create_table('dataapp_scope1mobilecombustion',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('record_date', sa.Date(), nullable=False),
    sa.Column('asset_id', sa.String(length=64), nullable=True),
    sa.Column('asset_name', sa.String(length=64), nullable=True),
    sa.Column('fuel_type', sa.String(length=16), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('unit', sa.String(length=5), nullable=False),
    sa.Column('mileage_km', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('work_hours', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('attachment', sa.String(length=255), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('creator_id', sa.GUID(length=16), nullable=True),
    sa.Column('approver_id', sa.GUID(length=16), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('reject_reason', sa.Text(), nullable=True),
    sa.Column('data_source', sa.String(length=20), nullable=False),
    sa.Column('collection_method', sa.String(length=20), nullable=False),
    sa.Column('confidence_level', sa.String(length=10), nullable=False),
    sa.Column('data_year_type', sa.String(length=20), nullable=False),
    sa.Column('data_year', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approver_id'], ['user_account.id'], name=op.f('fk_dataapp_scope1mobilecombustion_approver_id_user_account'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['creator_id'], ['user_account.id'], name=op.f('fk_dataapp_scope1mobilecombustion_creator_id_user_account'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dataapp_scope1mobilecombustion'))
    )
    with op.batch_alter_table('dataapp_scope1mobilecombustion', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dataapp_scope1mobilecombustion_approver_id'), ['approver_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dataapp_scope1mobilecombustion_creator_id'), ['creator_id'], unique=False)

    op.create_table('dataapp_scope1refrigerantleak',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=True),
    sa.Column('device_name', sa.String(length=64), nullable=True),
    sa.Column('fill_date', sa.Date(), nullable=False),
    sa.Column('refrigerant_type', sa.String(length=32), nullable=False),
    sa.Column('amount_kg', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('leak_type', sa.String(length=16), nullable=False),
    sa.Column('attachment', sa.String(length=255), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('creator_id', sa.GUID(length=16), nullable=True),
    sa.Column('approver_id', sa.GUID(length=16), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('reject_reason', sa.Text(), nullable=True),
    sa.Column('data_source', sa.String(length=20), nullable=False),
    sa.Column('collection_method', sa.String(length=20), nullable=False),
    sa.Column('confidence_level', sa.String(length=10), nullable=False),
    sa.Column('data_year_type', sa.String(length=20), nullable=False),
    sa.Column('data_year', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approver_id'], ['user_account.id'], name=op.f('fk_dataapp_scope1refrigerantleak_approver_id_user_account'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['creator_id'], ['user_account.id'], name=op.f('fk_dataapp_scope1refrigerantleak_creator_id_user_account'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dataapp_scope1refrigerantleak'))
    )
    with op.batch_alter_table('dataapp_scope1refrigerantleak', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dataapp_scope1refrigerantleak_approver_id'), ['approver_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dataapp_scope1refrigerantleak_creator_id'), ['creator_id'], unique=False)

    op.create_table('dataapp_scope1stationarycombustion',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('facility_name', sa.String(length=64), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('fuel_type', sa.String(length=16), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('unit', sa.String(length=5), nullable=False),
    sa.Column('meter_reading_start', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('meter_reading_end', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('attachment', sa.String(length=255), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('creator_id', sa.GUID(length=16), nullable=True),
    sa.Column('approver_id', sa.GUID(length=16), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('reject_reason', sa.Text(), nullable=True),
    sa.Column('data_source', sa.String(length=20), nullable=False),
    sa.Column('collection_method', sa.String(length=20), nullable=False),
    sa.Column('confidence_level', sa.String(length=10), nullable=False),
    sa.Column('data_year_type', sa.String(length=20), nullable=False),
    sa.Column('data_year', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approver_id'], ['user_account.id'], name=op.f('fk_dataapp_scope1stationarycombustion_approver_id_user_account'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['creator_id'], ['user_account.id'], name=op.f('fk_dataapp_scope1stationarycombustion_creator_id_user_account'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dataapp_scope1stationarycombustion'))
    )
    with op.batch_alter_table('dataapp_scope1stationarycombustion', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dataapp_scope1stationarycombustion_approver_id'), ['approver_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dataapp_scope1stationarycombustion_creator_id'), ['creator_id'], unique=False)

    op.create_table('dataapp_scope2electricitybill',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('account_number', sa.String(length=64), nullable=False),
    sa.Column('billing_month', sa.String(length=7), nullable=False),
    sa.Column('total_kwh', sa.Numeric(precision=16, scale=4), nullable=False),
    sa.Column('peak_kwh', sa.Numeric(precision=16, scale=4), nullable=True),
    sa.Column('flat_kwh', sa.Numeric(precision=16, scale=4), nullable=True),
    sa.Column('valley_kwh', sa.Numeric(precision=16, scale=4), nullable=True),
    sa.Column('amount_cny', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('attachment', sa.String(length=255), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('creator_id', sa.GUID(length=16), nullable=True),
    sa.Column('approver_id', sa.GUID(length=16), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('reject_reason', sa.Text(), nullable=True),
    sa.Column('data_source', sa.String(length=20), nullable=False),
    sa.Column('collection_method', sa.String(length=20), nullable=False),
    sa.Column('confidence_level', sa.String(length=10), nullable=False),
    sa.Column('data_year_type', sa.String(length=20), nullable=False),
    sa.Column('data_year', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approver_id'], ['user_account.id'], name=op.f('fk_dataapp_scope2electricitybill_approver_id_user_account'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['creator_id'], ['user_account.id'], name=op.f('fk_dataapp_scope2electricitybill_creator_id_user_account'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dataapp_scope2electricitybill'))
    )
    with op.batch_alter_table('dataapp_scope2electricitybill', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dataapp_scope2electricitybill_approver_id'), ['approver_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dataapp_scope2electricitybill_creator_id'), ['creator_id'], unique=False)

    op.create_table('dataapp_scope3thirdpartytransport',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('waybill_no', sa.String(length=64), nullable=False),
    sa.Column('origin', sa.String(length=128), nullable=False),
    sa.Column('destination', sa.String(length=128), nullable=False),
    sa.Column('vehicle_type', sa.String(length=32), nullable=False),
    sa.Column('distance_km', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('load_ton', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('fuel_amount', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('attachment', sa.String(length=255), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('creator_id', sa.GUID(length=16), nullable=True),
    sa.Column('approver_id', sa.GUID(length=16), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('reject_reason', sa.Text(), nullable=True),
    sa.Column('data_source', sa.String(length=20), nullable=False),
    sa.Column('collection_method', sa.String(length=20), nullable=False),
    sa.Column('confidence_level', sa.String(length=10), nullable=False),
    sa.Column('data_year_type', sa.String(length=20), nullable=False),
    sa.Column('data_year', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approver_id'], ['user_account.id'], name=op.f('fk_dataapp_scope3thirdpartytransport_approver_id_user_account'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['creator_id'], ['user_account.id'], name=op.f('fk_dataapp_scope3thirdpartytransport_creator_id_user_account'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dataapp_scope3thirdpartytransport'))
    )
    with op.batch_alter_table('dataapp_scope3thirdpartytransport', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dataapp_scope3thirdpartytransport_approver_id'), ['approver_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dataapp_scope3thirdpartytransport_creator_id'), ['creator_id'], unique=False)

    op.create_table('dataapp_scope3wastedisposal',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('weight_ton', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('treatment_method', sa.String(length=16), nullable=False),
    sa.Column('vendor_name', sa.String(length=128), nullable=True),
    sa.Column('attachment', sa.String(length=255), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('creator_id', sa.GUID(length=16), nullable=True),
    sa.Column('approver_id', sa.GUID(length=16), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('reject_reason', sa.Text(), nullable=True),
    sa.Column('data_source', sa.String(length=20), nullable=False),
    sa.Column('collection_method', sa.String(length=20), nullable=False),
    sa.Column('confidence_level', sa.String(length=10), nullable=False),
    sa.Column('data_year_type', sa.String(length=20), nullable=False),
    sa.Column('data_year', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approver_id'], ['user_account.id'], name=op.f('fk_dataapp_scope3wastedisposal_approver_id_user_account'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['creator_id'], ['user_account.id'], name=op.f('fk_dataapp_scope3wastedisposal_creator_id_user_account'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dataapp_scope3wastedisposal'))
    )
    with op.batch_alter_table('dataapp_scope3wastedisposal', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dataapp_scope3wastedisposal_approver_id'), ['approver_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dataapp_scope3wastedisposal_creator_id'), ['creator_id'], unique=False)

    op.create_table('dataapp_vedioalarmevent',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('event_type', sa.Integer(), nullable=False),
    sa.Column('event_desc', sa.String(length=300), nullable=True),
    sa.Column('event_time', sa.DateTime(), nullable=True),
    sa.Column('equipment_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('add_time', sa.DateTime(), nullable=True),
    sa.Column('is_handle', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['dataapp_videomonitor.id'], name=op.f('fk_dataapp_vedioalarmevent_equipment_id_dataapp_videomonitor'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dataapp_vedioalarmevent'))
    )
    with op.batch_alter_table('dataapp_vedioalarmevent', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dataapp_vedioalarmevent_equipment_id'), ['equipment_id'], unique=False)

    op.create_table('dataapp_warningrule',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('range_val', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'cockroachdb').with_variant(sa.ORA_JSONB(), 'oracle').with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True, comment='取值范围'),
    sa.Column('event_type', sa.Integer(), nullable=False),
    sa.Column('sector_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('table_name', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['sector_id'], ['dataapp_monitorsector.id'], name=op.f('fk_dataapp_warningrule_sector_id_dataapp_monitorsector'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dataapp_warningrule'))
    )
    with op.batch_alter_table('dataapp_warningrule', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dataapp_warningrule_sector_id'), ['sector_id'], unique=False)

    op.create_table('email_verification_token',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('user_id', sa.GUID(length=16), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTimeUTC(timezone=True), nullable=True),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], name=op.f('fk_email_verification_token_user_id_user_account'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_email_verification_token')),
    comment='Email verification tokens for user account verification'
    )
    with op.batch_alter_table('email_verification_token', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_verification_token_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_email_verification_token_user_id'), ['user_id'], unique=False)

    op.create_table('password_reset_token',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('user_id', sa.GUID(length=16), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTimeUTC(timezone=True), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], name=op.f('fk_password_reset_token_user_id_user_account'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_password_reset_token')),
    comment='Password reset tokens for secure password recovery'
    )
    with op.batch_alter_table('password_reset_token', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_password_reset_token_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_password_reset_token_user_id'), ['user_id'], unique=False)

    op.create_table('refresh_token',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('user_id', sa.GUID(length=16), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('family_id', sa.GUID(length=16), nullable=False),
    sa.Column('expires_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTimeUTC(timezone=True), nullable=True),
    sa.Column('device_info', sa.String(length=255), nullable=True),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], name=op.f('fk_refresh_token_user_id_user_account'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_token')),
    comment='JWT refresh tokens with rotation tracking'
    )
    with op.batch_alter_table('refresh_token', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refresh_token_family_id'), ['family_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_refresh_token_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_refresh_token_user_id'), ['user_id'], unique=False)

    op.create_table('team_invitation',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('team_id', sa.GUID(length=16), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_accepted', sa.Boolean(), nullable=False),
    sa.Column('invited_by_id', sa.GUID(length=16), nullable=True),
    sa.Column('invited_by_email', sa.String(), nullable=False),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['invited_by_id'], ['user_account.id'], name=op.f('fk_team_invitation_invited_by_id_user_account'), ondelete='set null'),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], name=op.f('fk_team_invitation_team_id_team'), ondelete='cascade'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_team_invitation'))
    )
    with op.batch_alter_table('team_invitation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_team_invitation_email'), ['email'], unique=False)

    op.create_table('team_member',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('user_id', sa.GUID(length=16), nullable=False),
    sa.Column('team_id', sa.GUID(length=16), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_owner', sa.Boolean(), nullable=False),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], name=op.f('fk_team_member_team_id_team'), ondelete='cascade'),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], name=op.f('fk_team_member_user_id_user_account'), ondelete='cascade'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_team_member')),
    sa.UniqueConstraint('user_id', 'team_id', name=op.f('uq_team_member_user_id'))
    )
    with op.batch_alter_table('team_member', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_team_member_role'), ['role'], unique=False)

    op.create_table('team_tag',
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], name=op.f('fk_team_tag_tag_id_tag'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], name=op.f('fk_team_tag_team_id_team'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('team_id', 'tag_id', name=op.f('pk_team_tag'))
    )
    op.create_table('user_account_oauth',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('user_id', sa.GUID(length=16), nullable=False),
    sa.Column('oauth_name', sa.String(length=100), nullable=False),
    sa.Column('access_token', sa.EncryptedString(key='136137cf918eac1dc8da4472c803a3481987a420d063c6278c053253cc225eab', backend=FernetBackend, length=None), nullable=False),
    sa.Column('expires_at', sa.Integer(), nullable=True),
    sa.Column('refresh_token', sa.EncryptedString(key='136137cf918eac1dc8da4472c803a3481987a420d063c6278c053253cc225eab', backend=FernetBackend, length=None), nullable=True),
    sa.Column('account_id', sa.String(length=320), nullable=False),
    sa.Column('account_email', sa.String(length=320), nullable=False),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scope', sa.Text(), nullable=True),
    sa.Column('provider_user_data', sa.JSON(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], name=op.f('fk_user_account_oauth_user_id_user_account'), ondelete='cascade'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_account_oauth')),
    comment='Registered OAUTH2 Accounts for Users'
    )
    with op.batch_alter_table('user_account_oauth', schema=None) as batch_op:
        batch_op.create_index('ix_oauth_provider_oauth_id', ['oauth_name', 'account_id'], unique=False)
        batch_op.create_index('ix_oauth_user_provider', ['user_id', 'oauth_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_account_oauth_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_account_oauth_oauth_name'), ['oauth_name'], unique=False)

    op.create_table('user_account_role',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('user_id', sa.GUID(length=16), nullable=False),
    sa.Column('role_id', sa.GUID(length=16), nullable=False),
    sa.Column('assigned_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], name=op.f('fk_user_account_role_role_id_role'), ondelete='cascade'),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], name=op.f('fk_user_account_role_user_id_user_account'), ondelete='cascade'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_account_role')),
    comment='Links a user to a specific role.'
    )
    op.create_table('dataapp_alarmevent',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('rule_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('event_type', sa.Integer(), nullable=False),
    sa.Column('event_desc', sa.String(length=300), nullable=True),
    sa.Column('event_time', sa.DateTime(), nullable=True),
    sa.Column('sector_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('equipment_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('add_time', sa.DateTime(), nullable=True),
    sa.Column('is_handle', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['dataapp_monitorequipment.id'], name=op.f('fk_dataapp_alarmevent_equipment_id_dataapp_monitorequipment'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rule_id'], ['dataapp_warningrule.id'], name=op.f('fk_dataapp_alarmevent_rule_id_dataapp_warningrule'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sector_id'], ['dataapp_monitorsector.id'], name=op.f('fk_dataapp_alarmevent_sector_id_dataapp_monitorsector'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dataapp_alarmevent'))
    )
    with op.batch_alter_table('dataapp_alarmevent', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dataapp_alarmevent_equipment_id'), ['equipment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dataapp_alarmevent_rule_id'), ['rule_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dataapp_alarmevent_sector_id'), ['sector_id'], unique=False)

    op.create_table('dataapp_ammeterindexvalue',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('equipment_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('zygdn', sa.Float(), nullable=True),
    sa.Column('fygdn', sa.Float(), nullable=True),
    sa.Column('zwgdn', sa.Float(), nullable=True),
    sa.Column('fwgdn', sa.Float(), nullable=True),
    sa.Column('zygdnsz', sa.Float(), nullable=True),
    sa.Column('fygdnsz', sa.Float(), nullable=True),
    sa.Column('zwgdnsz', sa.Float(), nullable=True),
    sa.Column('fwgdnsz', sa.Float(), nullable=True),
    sa.Column('reading_time', sa.DateTime(), nullable=True),
    sa.Column('ammeter_id', sa.String(length=20), nullable=True),
    sa.Column('ammeter_name', sa.String(length=30), nullable=True),
    sa.Column('address', sa.String(length=50), nullable=True),
    sa.Column('area_id', sa.String(length=20), nullable=True),
    sa.Column('area_name', sa.String(length=50), nullable=True),
    sa.Column('radio', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('data_source', sa.Integer(), nullable=True),
    sa.Column('add_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['dataapp_monitorequipment.id'], name=op.f('fk_dataapp_ammeterindexvalue_equipment_id_dataapp_monitorequipment'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dataapp_ammeterindexvalue'))
    )
    with op.batch_alter_table('dataapp_ammeterindexvalue', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dataapp_ammeterindexvalue_ammeter_id'), ['ammeter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dataapp_ammeterindexvalue_area_id'), ['area_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dataapp_ammeterindexvalue_equipment_id'), ['equipment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dataapp_ammeterindexvalue_reading_time'), ['reading_time'], unique=False)

    # ### end Alembic commands ###

def schema_downgrades() -> None:
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dataapp_ammeterindexvalue', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dataapp_ammeterindexvalue_reading_time'))
        batch_op.drop_index(batch_op.f('ix_dataapp_ammeterindexvalue_equipment_id'))
        batch_op.drop_index(batch_op.f('ix_dataapp_ammeterindexvalue_area_id'))
        batch_op.drop_index(batch_op.f('ix_dataapp_ammeterindexvalue_ammeter_id'))

    op.drop_table('dataapp_ammeterindexvalue')
    with op.batch_alter_table('dataapp_alarmevent', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dataapp_alarmevent_sector_id'))
        batch_op.drop_index(batch_op.f('ix_dataapp_alarmevent_rule_id'))
        batch_op.drop_index(batch_op.f('ix_dataapp_alarmevent_equipment_id'))

    op.drop_table('dataapp_alarmevent')
    op.drop_table('user_account_role')
    with op.batch_alter_table('user_account_oauth', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_account_oauth_oauth_name'))
        batch_op.drop_index(batch_op.f('ix_user_account_oauth_account_id'))
        batch_op.drop_index('ix_oauth_user_provider')
        batch_op.drop_index('ix_oauth_provider_oauth_id')

    op.drop_table('user_account_oauth')
    op.drop_table('team_tag')
    with op.batch_alter_table('team_member', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_team_member_role'))

    op.drop_table('team_member')
    with op.batch_alter_table('team_invitation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_team_invitation_email'))

    op.drop_table('team_invitation')
    with op.batch_alter_table('refresh_token', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refresh_token_user_id'))
        batch_op.drop_index(batch_op.f('ix_refresh_token_token_hash'))
        batch_op.drop_index(batch_op.f('ix_refresh_token_family_id'))

    op.drop_table('refresh_token')
    with op.batch_alter_table('password_reset_token', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_password_reset_token_user_id'))
        batch_op.drop_index(batch_op.f('ix_password_reset_token_token_hash'))

    op.drop_table('password_reset_token')
    with op.batch_alter_table('email_verification_token', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_verification_token_user_id'))
        batch_op.drop_index(batch_op.f('ix_email_verification_token_token_hash'))

    op.drop_table('email_verification_token')
    with op.batch_alter_table('dataapp_warningrule', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dataapp_warningrule_sector_id'))

    op.drop_table('dataapp_warningrule')
    with op.batch_alter_table('dataapp_vedioalarmevent', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dataapp_vedioalarmevent_equipment_id'))

    op.drop_table('dataapp_vedioalarmevent')
    with op.batch_alter_table('dataapp_scope3wastedisposal', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dataapp_scope3wastedisposal_creator_id'))
        batch_op.drop_index(batch_op.f('ix_dataapp_scope3wastedisposal_approver_id'))

    op.drop_table('dataapp_scope3wastedisposal')
    with op.batch_alter_table('dataapp_scope3thirdpartytransport', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dataapp_scope3thirdpartytransport_creator_id'))
        batch_op.drop_index(batch_op.f('ix_dataapp_scope3thirdpartytransport_approver_id'))

    op.drop_table('dataapp_scope3thirdpartytransport')
    with op.batch_alter_table('dataapp_scope2electricitybill', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dataapp_scope2electricitybill_creator_id'))
        batch_op.drop_index(batch_op.f('ix_dataapp_scope2electricitybill_approver_id'))

    op.drop_table('dataapp_scope2electricitybill')
    with op.batch_alter_table('dataapp_scope1stationarycombustion', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dataapp_scope1stationarycombustion_creator_id'))
        batch_op.drop_index(batch_op.f('ix_dataapp_scope1stationarycombustion_approver_id'))

    op.drop_table('dataapp_scope1stationarycombustion')
    with op.batch_alter_table('dataapp_scope1refrigerantleak', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dataapp_scope1refrigerantleak_creator_id'))
        batch_op.drop_index(batch_op.f('ix_dataapp_scope1refrigerantleak_approver_id'))

    op.drop_table('dataapp_scope1refrigerantleak')
    with op.batch_alter_table('dataapp_scope1mobilecombustion', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dataapp_scope1mobilecombustion_creator_id'))
        batch_op.drop_index(batch_op.f('ix_dataapp_scope1mobilecombustion_approver_id'))

    op.drop_table('dataapp_scope1mobilecombustion')
    with op.batch_alter_table('dataapp_monitorsectorphoto', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dataapp_monitorsectorphoto_sector_id'))

    op.drop_table('dataapp_monitorsectorphoto')
    with op.batch_alter_table('dataapp_monitorequipment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dataapp_monitorequipment_sector_id'))
        batch_op.drop_index(batch_op.f('ix_dataapp_monitorequipment_code'))

    op.drop_table('dataapp_monitorequipment')
    with op.batch_alter_table('dataapp_carbonauditlog', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dataapp_carbonauditlog_operator_id'))

    op.drop_table('dataapp_carbonauditlog')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_target_type'))
        batch_op.drop_index(batch_op.f('ix_audit_log_target_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_actor_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_action'))

    op.drop_table('audit_log')
    with op.batch_alter_table('user_account', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_account_username'))
        batch_op.drop_index(batch_op.f('ix_user_account_email'))

    op.drop_table('user_account')
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.drop_index('ix_team_slug_unique')
        batch_op.drop_index(batch_op.f('ix_team_name'))

    op.drop_table('team')
    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.drop_index('ix_tag_slug_unique')

    op.drop_table('tag')
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.drop_index('ix_role_slug_unique')

    op.drop_table('role')
    op.drop_table('dataapp_videomonitor')
    op.drop_table('dataapp_outmoney')
    op.drop_table('dataapp_monitorsector')
    with op.batch_alter_table('dataapp_iottelemetry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dataapp_iottelemetry_site_id'))
        batch_op.drop_index(batch_op.f('ix_dataapp_iottelemetry_reading_time'))
        batch_op.drop_index(batch_op.f('ix_dataapp_iottelemetry_device_id'))

    op.drop_table('dataapp_iottelemetry')
    op.drop_table('dataapp_inmoney')
    op.drop_table('dataapp_enterpriseinfo')
    op.drop_table('dataapp_energystoragevalue')
    op.drop_table('dataapp_employeecommute')
    op.drop_table('dataapp_emissionfactor')
    op.drop_table('dataapp_apiresultkeymapping')
    # ### end Alembic commands ###

def data_upgrades() -> None:
    """Add any optional data upgrade migrations here!"""

def data_downgrades() -> None:
    """Add any optional data downgrade migrations here!"""
