/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AppRouteImport } from './routes/_app'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PublicVerifyEmailRouteImport } from './routes/_public/verify-email'
import { Route as PublicTermsRouteImport } from './routes/_public/terms'
import { Route as PublicSignupRouteImport } from './routes/_public/signup'
import { Route as PublicResetPasswordRouteImport } from './routes/_public/reset-password'
import { Route as PublicPrivacyRouteImport } from './routes/_public/privacy'
import { Route as PublicMfaChallengeRouteImport } from './routes/_public/mfa-challenge'
import { Route as PublicLoginRouteImport } from './routes/_public/login'
import { Route as PublicForgotPasswordRouteImport } from './routes/_public/forgot-password'
import { Route as PublicAboutRouteImport } from './routes/_public/about'
import { Route as AppTeamsRouteImport } from './routes/_app/teams'
import { Route as AppPlatformRouteImport } from './routes/_app/platform'
import { Route as AppHomeRouteImport } from './routes/_app/home'
import { Route as AppCarbonRouteImport } from './routes/_app/carbon'
import { Route as AppAdminRouteImport } from './routes/_app/admin'
import { Route as AppTeamsIndexRouteImport } from './routes/_app/teams/index'
import { Route as AppProfileIndexRouteImport } from './routes/_app/profile/index'
import { Route as AppCarbonIndexRouteImport } from './routes/_app/carbon/index'
import { Route as AppAdminIndexRouteImport } from './routes/_app/admin/index'
import { Route as AppTeamsNewRouteImport } from './routes/_app/teams/new'
import { Route as AppTeamsTeamIdRouteImport } from './routes/_app/teams/$teamId'
import { Route as AppTasksSchedulesRouteImport } from './routes/_app/tasks/schedules'
import { Route as AppTasksIntervalRouteImport } from './routes/_app/tasks/interval'
import { Route as AppTasksCrontabRouteImport } from './routes/_app/tasks/crontab'
import { Route as AppDataVideoAlarmEventsRouteImport } from './routes/_app/data/video-alarm-events'
import { Route as AppDataVideoRouteImport } from './routes/_app/data/video'
import { Route as AppDataTerminalsRouteImport } from './routes/_app/data/terminals'
import { Route as AppDataOutboundRouteImport } from './routes/_app/data/outbound'
import { Route as AppDataMonitorAreaRouteImport } from './routes/_app/data/monitor-area'
import { Route as AppDataMeterRouteImport } from './routes/_app/data/meter'
import { Route as AppDataInboundRouteImport } from './routes/_app/data/inbound'
import { Route as AppDataEnergyStorageRouteImport } from './routes/_app/data/energy-storage'
import { Route as AppDataCompanyRouteImport } from './routes/_app/data/company'
import { Route as AppDataCommuteRouteImport } from './routes/_app/data/commute'
import { Route as AppDataApiKeyMappingRouteImport } from './routes/_app/data/api-key-mapping'
import { Route as AppDataAlarmRulesRouteImport } from './routes/_app/data/alarm-rules'
import { Route as AppDataAlarmEventsRouteImport } from './routes/_app/data/alarm-events'
import { Route as AppCarbonPage4RouteImport } from './routes/_app/carbon/page4'
import { Route as AppCarbonPage3RouteImport } from './routes/_app/carbon/page3'
import { Route as AppCarbonPage2RouteImport } from './routes/_app/carbon/page2'
import { Route as AppCarbonMapRouteImport } from './routes/_app/carbon/map'
import { Route as AppCarbonHwpmRouteImport } from './routes/_app/carbon/hwpm'
import { Route as AppCarbonMgmtScope3WasteRouteImport } from './routes/_app/carbon-mgmt/scope3-waste'
import { Route as AppCarbonMgmtScope3TransportRouteImport } from './routes/_app/carbon-mgmt/scope3-transport'
import { Route as AppCarbonMgmtScope2BillRouteImport } from './routes/_app/carbon-mgmt/scope2-bill'
import { Route as AppCarbonMgmtScope1StationaryRouteImport } from './routes/_app/carbon-mgmt/scope1-stationary'
import { Route as AppCarbonMgmtScope1RefrigerantRouteImport } from './routes/_app/carbon-mgmt/scope1-refrigerant'
import { Route as AppCarbonMgmtScope1MobileRouteImport } from './routes/_app/carbon-mgmt/scope1-mobile'
import { Route as AppCarbonMgmtIotRouteImport } from './routes/_app/carbon-mgmt/iot'
import { Route as AppCarbonMgmtFactorsRouteImport } from './routes/_app/carbon-mgmt/factors'
import { Route as AppCarbonMgmtAuditRouteImport } from './routes/_app/carbon-mgmt/audit'
import { Route as AppAuthUsersRouteImport } from './routes/_app/auth/users'
import { Route as AppAuthRolesRouteImport } from './routes/_app/auth/roles'
import { Route as AppAdminAuditRouteImport } from './routes/_app/admin/audit'
import { Route as AppAdminUsersIndexRouteImport } from './routes/_app/admin/users/index'
import { Route as AppAdminTeamsIndexRouteImport } from './routes/_app/admin/teams/index'
import { Route as PublicAuthGoogleCallbackRouteImport } from './routes/_public/auth/google/callback'
import { Route as PublicAuthGithubCallbackRouteImport } from './routes/_public/auth/github/callback'
import { Route as AppAdminUsersUserIdRouteImport } from './routes/_app/admin/users/$userId'
import { Route as AppAdminTeamsTeamIdRouteImport } from './routes/_app/admin/teams/$teamId'
import { Route as AppTeamsTeamIdInvitationsInvitationIdAcceptRouteImport } from './routes/_app/teams/$teamId/invitations/$invitationId/accept'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicVerifyEmailRoute = PublicVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => PublicRoute,
} as any)
const PublicTermsRoute = PublicTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => PublicRoute,
} as any)
const PublicSignupRoute = PublicSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => PublicRoute,
} as any)
const PublicResetPasswordRoute = PublicResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => PublicRoute,
} as any)
const PublicPrivacyRoute = PublicPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => PublicRoute,
} as any)
const PublicMfaChallengeRoute = PublicMfaChallengeRouteImport.update({
  id: '/mfa-challenge',
  path: '/mfa-challenge',
  getParentRoute: () => PublicRoute,
} as any)
const PublicLoginRoute = PublicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicRoute,
} as any)
const PublicForgotPasswordRoute = PublicForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAboutRoute = PublicAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => PublicRoute,
} as any)
const AppTeamsRoute = AppTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => AppRoute,
} as any)
const AppPlatformRoute = AppPlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => AppRoute,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)
const AppCarbonRoute = AppCarbonRouteImport.update({
  id: '/carbon',
  path: '/carbon',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamsIndexRoute = AppTeamsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppTeamsRoute,
} as any)
const AppProfileIndexRoute = AppProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => AppRoute,
} as any)
const AppCarbonIndexRoute = AppCarbonIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppCarbonRoute,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppTeamsNewRoute = AppTeamsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppTeamsRoute,
} as any)
const AppTeamsTeamIdRoute = AppTeamsTeamIdRouteImport.update({
  id: '/$teamId',
  path: '/$teamId',
  getParentRoute: () => AppTeamsRoute,
} as any)
const AppTasksSchedulesRoute = AppTasksSchedulesRouteImport.update({
  id: '/tasks/schedules',
  path: '/tasks/schedules',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksIntervalRoute = AppTasksIntervalRouteImport.update({
  id: '/tasks/interval',
  path: '/tasks/interval',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksCrontabRoute = AppTasksCrontabRouteImport.update({
  id: '/tasks/crontab',
  path: '/tasks/crontab',
  getParentRoute: () => AppRoute,
} as any)
const AppDataVideoAlarmEventsRoute = AppDataVideoAlarmEventsRouteImport.update({
  id: '/data/video-alarm-events',
  path: '/data/video-alarm-events',
  getParentRoute: () => AppRoute,
} as any)
const AppDataVideoRoute = AppDataVideoRouteImport.update({
  id: '/data/video',
  path: '/data/video',
  getParentRoute: () => AppRoute,
} as any)
const AppDataTerminalsRoute = AppDataTerminalsRouteImport.update({
  id: '/data/terminals',
  path: '/data/terminals',
  getParentRoute: () => AppRoute,
} as any)
const AppDataOutboundRoute = AppDataOutboundRouteImport.update({
  id: '/data/outbound',
  path: '/data/outbound',
  getParentRoute: () => AppRoute,
} as any)
const AppDataMonitorAreaRoute = AppDataMonitorAreaRouteImport.update({
  id: '/data/monitor-area',
  path: '/data/monitor-area',
  getParentRoute: () => AppRoute,
} as any)
const AppDataMeterRoute = AppDataMeterRouteImport.update({
  id: '/data/meter',
  path: '/data/meter',
  getParentRoute: () => AppRoute,
} as any)
const AppDataInboundRoute = AppDataInboundRouteImport.update({
  id: '/data/inbound',
  path: '/data/inbound',
  getParentRoute: () => AppRoute,
} as any)
const AppDataEnergyStorageRoute = AppDataEnergyStorageRouteImport.update({
  id: '/data/energy-storage',
  path: '/data/energy-storage',
  getParentRoute: () => AppRoute,
} as any)
const AppDataCompanyRoute = AppDataCompanyRouteImport.update({
  id: '/data/company',
  path: '/data/company',
  getParentRoute: () => AppRoute,
} as any)
const AppDataCommuteRoute = AppDataCommuteRouteImport.update({
  id: '/data/commute',
  path: '/data/commute',
  getParentRoute: () => AppRoute,
} as any)
const AppDataApiKeyMappingRoute = AppDataApiKeyMappingRouteImport.update({
  id: '/data/api-key-mapping',
  path: '/data/api-key-mapping',
  getParentRoute: () => AppRoute,
} as any)
const AppDataAlarmRulesRoute = AppDataAlarmRulesRouteImport.update({
  id: '/data/alarm-rules',
  path: '/data/alarm-rules',
  getParentRoute: () => AppRoute,
} as any)
const AppDataAlarmEventsRoute = AppDataAlarmEventsRouteImport.update({
  id: '/data/alarm-events',
  path: '/data/alarm-events',
  getParentRoute: () => AppRoute,
} as any)
const AppCarbonPage4Route = AppCarbonPage4RouteImport.update({
  id: '/page4',
  path: '/page4',
  getParentRoute: () => AppCarbonRoute,
} as any)
const AppCarbonPage3Route = AppCarbonPage3RouteImport.update({
  id: '/page3',
  path: '/page3',
  getParentRoute: () => AppCarbonRoute,
} as any)
const AppCarbonPage2Route = AppCarbonPage2RouteImport.update({
  id: '/page2',
  path: '/page2',
  getParentRoute: () => AppCarbonRoute,
} as any)
const AppCarbonMapRoute = AppCarbonMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AppCarbonRoute,
} as any)
const AppCarbonHwpmRoute = AppCarbonHwpmRouteImport.update({
  id: '/hwpm',
  path: '/hwpm',
  getParentRoute: () => AppCarbonRoute,
} as any)
const AppCarbonMgmtScope3WasteRoute =
  AppCarbonMgmtScope3WasteRouteImport.update({
    id: '/carbon-mgmt/scope3-waste',
    path: '/carbon-mgmt/scope3-waste',
    getParentRoute: () => AppRoute,
  } as any)
const AppCarbonMgmtScope3TransportRoute =
  AppCarbonMgmtScope3TransportRouteImport.update({
    id: '/carbon-mgmt/scope3-transport',
    path: '/carbon-mgmt/scope3-transport',
    getParentRoute: () => AppRoute,
  } as any)
const AppCarbonMgmtScope2BillRoute = AppCarbonMgmtScope2BillRouteImport.update({
  id: '/carbon-mgmt/scope2-bill',
  path: '/carbon-mgmt/scope2-bill',
  getParentRoute: () => AppRoute,
} as any)
const AppCarbonMgmtScope1StationaryRoute =
  AppCarbonMgmtScope1StationaryRouteImport.update({
    id: '/carbon-mgmt/scope1-stationary',
    path: '/carbon-mgmt/scope1-stationary',
    getParentRoute: () => AppRoute,
  } as any)
const AppCarbonMgmtScope1RefrigerantRoute =
  AppCarbonMgmtScope1RefrigerantRouteImport.update({
    id: '/carbon-mgmt/scope1-refrigerant',
    path: '/carbon-mgmt/scope1-refrigerant',
    getParentRoute: () => AppRoute,
  } as any)
const AppCarbonMgmtScope1MobileRoute =
  AppCarbonMgmtScope1MobileRouteImport.update({
    id: '/carbon-mgmt/scope1-mobile',
    path: '/carbon-mgmt/scope1-mobile',
    getParentRoute: () => AppRoute,
  } as any)
const AppCarbonMgmtIotRoute = AppCarbonMgmtIotRouteImport.update({
  id: '/carbon-mgmt/iot',
  path: '/carbon-mgmt/iot',
  getParentRoute: () => AppRoute,
} as any)
const AppCarbonMgmtFactorsRoute = AppCarbonMgmtFactorsRouteImport.update({
  id: '/carbon-mgmt/factors',
  path: '/carbon-mgmt/factors',
  getParentRoute: () => AppRoute,
} as any)
const AppCarbonMgmtAuditRoute = AppCarbonMgmtAuditRouteImport.update({
  id: '/carbon-mgmt/audit',
  path: '/carbon-mgmt/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppAuthUsersRoute = AppAuthUsersRouteImport.update({
  id: '/auth/users',
  path: '/auth/users',
  getParentRoute: () => AppRoute,
} as any)
const AppAuthRolesRoute = AppAuthRolesRouteImport.update({
  id: '/auth/roles',
  path: '/auth/roles',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminAuditRoute = AppAdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminUsersIndexRoute = AppAdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminTeamsIndexRoute = AppAdminTeamsIndexRouteImport.update({
  id: '/teams/',
  path: '/teams/',
  getParentRoute: () => AppAdminRoute,
} as any)
const PublicAuthGoogleCallbackRoute =
  PublicAuthGoogleCallbackRouteImport.update({
    id: '/auth/google/callback',
    path: '/auth/google/callback',
    getParentRoute: () => PublicRoute,
  } as any)
const PublicAuthGithubCallbackRoute =
  PublicAuthGithubCallbackRouteImport.update({
    id: '/auth/github/callback',
    path: '/auth/github/callback',
    getParentRoute: () => PublicRoute,
  } as any)
const AppAdminUsersUserIdRoute = AppAdminUsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminTeamsTeamIdRoute = AppAdminTeamsTeamIdRouteImport.update({
  id: '/teams/$teamId',
  path: '/teams/$teamId',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppTeamsTeamIdInvitationsInvitationIdAcceptRoute =
  AppTeamsTeamIdInvitationsInvitationIdAcceptRouteImport.update({
    id: '/invitations/$invitationId/accept',
    path: '/invitations/$invitationId/accept',
    getParentRoute: () => AppTeamsTeamIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/admin': typeof AppAdminRouteWithChildren
  '/carbon': typeof AppCarbonRouteWithChildren
  '/home': typeof AppHomeRoute
  '/platform': typeof AppPlatformRoute
  '/teams': typeof AppTeamsRouteWithChildren
  '/about': typeof PublicAboutRoute
  '/forgot-password': typeof PublicForgotPasswordRoute
  '/login': typeof PublicLoginRoute
  '/mfa-challenge': typeof PublicMfaChallengeRoute
  '/privacy': typeof PublicPrivacyRoute
  '/reset-password': typeof PublicResetPasswordRoute
  '/signup': typeof PublicSignupRoute
  '/terms': typeof PublicTermsRoute
  '/verify-email': typeof PublicVerifyEmailRoute
  '/admin/audit': typeof AppAdminAuditRoute
  '/auth/roles': typeof AppAuthRolesRoute
  '/auth/users': typeof AppAuthUsersRoute
  '/carbon-mgmt/audit': typeof AppCarbonMgmtAuditRoute
  '/carbon-mgmt/factors': typeof AppCarbonMgmtFactorsRoute
  '/carbon-mgmt/iot': typeof AppCarbonMgmtIotRoute
  '/carbon-mgmt/scope1-mobile': typeof AppCarbonMgmtScope1MobileRoute
  '/carbon-mgmt/scope1-refrigerant': typeof AppCarbonMgmtScope1RefrigerantRoute
  '/carbon-mgmt/scope1-stationary': typeof AppCarbonMgmtScope1StationaryRoute
  '/carbon-mgmt/scope2-bill': typeof AppCarbonMgmtScope2BillRoute
  '/carbon-mgmt/scope3-transport': typeof AppCarbonMgmtScope3TransportRoute
  '/carbon-mgmt/scope3-waste': typeof AppCarbonMgmtScope3WasteRoute
  '/carbon/hwpm': typeof AppCarbonHwpmRoute
  '/carbon/map': typeof AppCarbonMapRoute
  '/carbon/page2': typeof AppCarbonPage2Route
  '/carbon/page3': typeof AppCarbonPage3Route
  '/carbon/page4': typeof AppCarbonPage4Route
  '/data/alarm-events': typeof AppDataAlarmEventsRoute
  '/data/alarm-rules': typeof AppDataAlarmRulesRoute
  '/data/api-key-mapping': typeof AppDataApiKeyMappingRoute
  '/data/commute': typeof AppDataCommuteRoute
  '/data/company': typeof AppDataCompanyRoute
  '/data/energy-storage': typeof AppDataEnergyStorageRoute
  '/data/inbound': typeof AppDataInboundRoute
  '/data/meter': typeof AppDataMeterRoute
  '/data/monitor-area': typeof AppDataMonitorAreaRoute
  '/data/outbound': typeof AppDataOutboundRoute
  '/data/terminals': typeof AppDataTerminalsRoute
  '/data/video': typeof AppDataVideoRoute
  '/data/video-alarm-events': typeof AppDataVideoAlarmEventsRoute
  '/tasks/crontab': typeof AppTasksCrontabRoute
  '/tasks/interval': typeof AppTasksIntervalRoute
  '/tasks/schedules': typeof AppTasksSchedulesRoute
  '/teams/$teamId': typeof AppTeamsTeamIdRouteWithChildren
  '/teams/new': typeof AppTeamsNewRoute
  '/admin/': typeof AppAdminIndexRoute
  '/carbon/': typeof AppCarbonIndexRoute
  '/profile/': typeof AppProfileIndexRoute
  '/teams/': typeof AppTeamsIndexRoute
  '/admin/teams/$teamId': typeof AppAdminTeamsTeamIdRoute
  '/admin/users/$userId': typeof AppAdminUsersUserIdRoute
  '/auth/github/callback': typeof PublicAuthGithubCallbackRoute
  '/auth/google/callback': typeof PublicAuthGoogleCallbackRoute
  '/admin/teams/': typeof AppAdminTeamsIndexRoute
  '/admin/users/': typeof AppAdminUsersIndexRoute
  '/teams/$teamId/invitations/$invitationId/accept': typeof AppTeamsTeamIdInvitationsInvitationIdAcceptRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/home': typeof AppHomeRoute
  '/platform': typeof AppPlatformRoute
  '/about': typeof PublicAboutRoute
  '/forgot-password': typeof PublicForgotPasswordRoute
  '/login': typeof PublicLoginRoute
  '/mfa-challenge': typeof PublicMfaChallengeRoute
  '/privacy': typeof PublicPrivacyRoute
  '/reset-password': typeof PublicResetPasswordRoute
  '/signup': typeof PublicSignupRoute
  '/terms': typeof PublicTermsRoute
  '/verify-email': typeof PublicVerifyEmailRoute
  '/admin/audit': typeof AppAdminAuditRoute
  '/auth/roles': typeof AppAuthRolesRoute
  '/auth/users': typeof AppAuthUsersRoute
  '/carbon-mgmt/audit': typeof AppCarbonMgmtAuditRoute
  '/carbon-mgmt/factors': typeof AppCarbonMgmtFactorsRoute
  '/carbon-mgmt/iot': typeof AppCarbonMgmtIotRoute
  '/carbon-mgmt/scope1-mobile': typeof AppCarbonMgmtScope1MobileRoute
  '/carbon-mgmt/scope1-refrigerant': typeof AppCarbonMgmtScope1RefrigerantRoute
  '/carbon-mgmt/scope1-stationary': typeof AppCarbonMgmtScope1StationaryRoute
  '/carbon-mgmt/scope2-bill': typeof AppCarbonMgmtScope2BillRoute
  '/carbon-mgmt/scope3-transport': typeof AppCarbonMgmtScope3TransportRoute
  '/carbon-mgmt/scope3-waste': typeof AppCarbonMgmtScope3WasteRoute
  '/carbon/hwpm': typeof AppCarbonHwpmRoute
  '/carbon/map': typeof AppCarbonMapRoute
  '/carbon/page2': typeof AppCarbonPage2Route
  '/carbon/page3': typeof AppCarbonPage3Route
  '/carbon/page4': typeof AppCarbonPage4Route
  '/data/alarm-events': typeof AppDataAlarmEventsRoute
  '/data/alarm-rules': typeof AppDataAlarmRulesRoute
  '/data/api-key-mapping': typeof AppDataApiKeyMappingRoute
  '/data/commute': typeof AppDataCommuteRoute
  '/data/company': typeof AppDataCompanyRoute
  '/data/energy-storage': typeof AppDataEnergyStorageRoute
  '/data/inbound': typeof AppDataInboundRoute
  '/data/meter': typeof AppDataMeterRoute
  '/data/monitor-area': typeof AppDataMonitorAreaRoute
  '/data/outbound': typeof AppDataOutboundRoute
  '/data/terminals': typeof AppDataTerminalsRoute
  '/data/video': typeof AppDataVideoRoute
  '/data/video-alarm-events': typeof AppDataVideoAlarmEventsRoute
  '/tasks/crontab': typeof AppTasksCrontabRoute
  '/tasks/interval': typeof AppTasksIntervalRoute
  '/tasks/schedules': typeof AppTasksSchedulesRoute
  '/teams/$teamId': typeof AppTeamsTeamIdRouteWithChildren
  '/teams/new': typeof AppTeamsNewRoute
  '/admin': typeof AppAdminIndexRoute
  '/carbon': typeof AppCarbonIndexRoute
  '/profile': typeof AppProfileIndexRoute
  '/teams': typeof AppTeamsIndexRoute
  '/admin/teams/$teamId': typeof AppAdminTeamsTeamIdRoute
  '/admin/users/$userId': typeof AppAdminUsersUserIdRoute
  '/auth/github/callback': typeof PublicAuthGithubCallbackRoute
  '/auth/google/callback': typeof PublicAuthGoogleCallbackRoute
  '/admin/teams': typeof AppAdminTeamsIndexRoute
  '/admin/users': typeof AppAdminUsersIndexRoute
  '/teams/$teamId/invitations/$invitationId/accept': typeof AppTeamsTeamIdInvitationsInvitationIdAcceptRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/_app': typeof AppRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_app/admin': typeof AppAdminRouteWithChildren
  '/_app/carbon': typeof AppCarbonRouteWithChildren
  '/_app/home': typeof AppHomeRoute
  '/_app/platform': typeof AppPlatformRoute
  '/_app/teams': typeof AppTeamsRouteWithChildren
  '/_public/about': typeof PublicAboutRoute
  '/_public/forgot-password': typeof PublicForgotPasswordRoute
  '/_public/login': typeof PublicLoginRoute
  '/_public/mfa-challenge': typeof PublicMfaChallengeRoute
  '/_public/privacy': typeof PublicPrivacyRoute
  '/_public/reset-password': typeof PublicResetPasswordRoute
  '/_public/signup': typeof PublicSignupRoute
  '/_public/terms': typeof PublicTermsRoute
  '/_public/verify-email': typeof PublicVerifyEmailRoute
  '/_app/admin/audit': typeof AppAdminAuditRoute
  '/_app/auth/roles': typeof AppAuthRolesRoute
  '/_app/auth/users': typeof AppAuthUsersRoute
  '/_app/carbon-mgmt/audit': typeof AppCarbonMgmtAuditRoute
  '/_app/carbon-mgmt/factors': typeof AppCarbonMgmtFactorsRoute
  '/_app/carbon-mgmt/iot': typeof AppCarbonMgmtIotRoute
  '/_app/carbon-mgmt/scope1-mobile': typeof AppCarbonMgmtScope1MobileRoute
  '/_app/carbon-mgmt/scope1-refrigerant': typeof AppCarbonMgmtScope1RefrigerantRoute
  '/_app/carbon-mgmt/scope1-stationary': typeof AppCarbonMgmtScope1StationaryRoute
  '/_app/carbon-mgmt/scope2-bill': typeof AppCarbonMgmtScope2BillRoute
  '/_app/carbon-mgmt/scope3-transport': typeof AppCarbonMgmtScope3TransportRoute
  '/_app/carbon-mgmt/scope3-waste': typeof AppCarbonMgmtScope3WasteRoute
  '/_app/carbon/hwpm': typeof AppCarbonHwpmRoute
  '/_app/carbon/map': typeof AppCarbonMapRoute
  '/_app/carbon/page2': typeof AppCarbonPage2Route
  '/_app/carbon/page3': typeof AppCarbonPage3Route
  '/_app/carbon/page4': typeof AppCarbonPage4Route
  '/_app/data/alarm-events': typeof AppDataAlarmEventsRoute
  '/_app/data/alarm-rules': typeof AppDataAlarmRulesRoute
  '/_app/data/api-key-mapping': typeof AppDataApiKeyMappingRoute
  '/_app/data/commute': typeof AppDataCommuteRoute
  '/_app/data/company': typeof AppDataCompanyRoute
  '/_app/data/energy-storage': typeof AppDataEnergyStorageRoute
  '/_app/data/inbound': typeof AppDataInboundRoute
  '/_app/data/meter': typeof AppDataMeterRoute
  '/_app/data/monitor-area': typeof AppDataMonitorAreaRoute
  '/_app/data/outbound': typeof AppDataOutboundRoute
  '/_app/data/terminals': typeof AppDataTerminalsRoute
  '/_app/data/video': typeof AppDataVideoRoute
  '/_app/data/video-alarm-events': typeof AppDataVideoAlarmEventsRoute
  '/_app/tasks/crontab': typeof AppTasksCrontabRoute
  '/_app/tasks/interval': typeof AppTasksIntervalRoute
  '/_app/tasks/schedules': typeof AppTasksSchedulesRoute
  '/_app/teams/$teamId': typeof AppTeamsTeamIdRouteWithChildren
  '/_app/teams/new': typeof AppTeamsNewRoute
  '/_app/admin/': typeof AppAdminIndexRoute
  '/_app/carbon/': typeof AppCarbonIndexRoute
  '/_app/profile/': typeof AppProfileIndexRoute
  '/_app/teams/': typeof AppTeamsIndexRoute
  '/_app/admin/teams/$teamId': typeof AppAdminTeamsTeamIdRoute
  '/_app/admin/users/$userId': typeof AppAdminUsersUserIdRoute
  '/_public/auth/github/callback': typeof PublicAuthGithubCallbackRoute
  '/_public/auth/google/callback': typeof PublicAuthGoogleCallbackRoute
  '/_app/admin/teams/': typeof AppAdminTeamsIndexRoute
  '/_app/admin/users/': typeof AppAdminUsersIndexRoute
  '/_app/teams/$teamId/invitations/$invitationId/accept': typeof AppTeamsTeamIdInvitationsInvitationIdAcceptRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/admin'
    | '/carbon'
    | '/home'
    | '/platform'
    | '/teams'
    | '/about'
    | '/forgot-password'
    | '/login'
    | '/mfa-challenge'
    | '/privacy'
    | '/reset-password'
    | '/signup'
    | '/terms'
    | '/verify-email'
    | '/admin/audit'
    | '/auth/roles'
    | '/auth/users'
    | '/carbon-mgmt/audit'
    | '/carbon-mgmt/factors'
    | '/carbon-mgmt/iot'
    | '/carbon-mgmt/scope1-mobile'
    | '/carbon-mgmt/scope1-refrigerant'
    | '/carbon-mgmt/scope1-stationary'
    | '/carbon-mgmt/scope2-bill'
    | '/carbon-mgmt/scope3-transport'
    | '/carbon-mgmt/scope3-waste'
    | '/carbon/hwpm'
    | '/carbon/map'
    | '/carbon/page2'
    | '/carbon/page3'
    | '/carbon/page4'
    | '/data/alarm-events'
    | '/data/alarm-rules'
    | '/data/api-key-mapping'
    | '/data/commute'
    | '/data/company'
    | '/data/energy-storage'
    | '/data/inbound'
    | '/data/meter'
    | '/data/monitor-area'
    | '/data/outbound'
    | '/data/terminals'
    | '/data/video'
    | '/data/video-alarm-events'
    | '/tasks/crontab'
    | '/tasks/interval'
    | '/tasks/schedules'
    | '/teams/$teamId'
    | '/teams/new'
    | '/admin/'
    | '/carbon/'
    | '/profile/'
    | '/teams/'
    | '/admin/teams/$teamId'
    | '/admin/users/$userId'
    | '/auth/github/callback'
    | '/auth/google/callback'
    | '/admin/teams/'
    | '/admin/users/'
    | '/teams/$teamId/invitations/$invitationId/accept'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/home'
    | '/platform'
    | '/about'
    | '/forgot-password'
    | '/login'
    | '/mfa-challenge'
    | '/privacy'
    | '/reset-password'
    | '/signup'
    | '/terms'
    | '/verify-email'
    | '/admin/audit'
    | '/auth/roles'
    | '/auth/users'
    | '/carbon-mgmt/audit'
    | '/carbon-mgmt/factors'
    | '/carbon-mgmt/iot'
    | '/carbon-mgmt/scope1-mobile'
    | '/carbon-mgmt/scope1-refrigerant'
    | '/carbon-mgmt/scope1-stationary'
    | '/carbon-mgmt/scope2-bill'
    | '/carbon-mgmt/scope3-transport'
    | '/carbon-mgmt/scope3-waste'
    | '/carbon/hwpm'
    | '/carbon/map'
    | '/carbon/page2'
    | '/carbon/page3'
    | '/carbon/page4'
    | '/data/alarm-events'
    | '/data/alarm-rules'
    | '/data/api-key-mapping'
    | '/data/commute'
    | '/data/company'
    | '/data/energy-storage'
    | '/data/inbound'
    | '/data/meter'
    | '/data/monitor-area'
    | '/data/outbound'
    | '/data/terminals'
    | '/data/video'
    | '/data/video-alarm-events'
    | '/tasks/crontab'
    | '/tasks/interval'
    | '/tasks/schedules'
    | '/teams/$teamId'
    | '/teams/new'
    | '/admin'
    | '/carbon'
    | '/profile'
    | '/teams'
    | '/admin/teams/$teamId'
    | '/admin/users/$userId'
    | '/auth/github/callback'
    | '/auth/google/callback'
    | '/admin/teams'
    | '/admin/users'
    | '/teams/$teamId/invitations/$invitationId/accept'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/_app'
    | '/_public'
    | '/_app/admin'
    | '/_app/carbon'
    | '/_app/home'
    | '/_app/platform'
    | '/_app/teams'
    | '/_public/about'
    | '/_public/forgot-password'
    | '/_public/login'
    | '/_public/mfa-challenge'
    | '/_public/privacy'
    | '/_public/reset-password'
    | '/_public/signup'
    | '/_public/terms'
    | '/_public/verify-email'
    | '/_app/admin/audit'
    | '/_app/auth/roles'
    | '/_app/auth/users'
    | '/_app/carbon-mgmt/audit'
    | '/_app/carbon-mgmt/factors'
    | '/_app/carbon-mgmt/iot'
    | '/_app/carbon-mgmt/scope1-mobile'
    | '/_app/carbon-mgmt/scope1-refrigerant'
    | '/_app/carbon-mgmt/scope1-stationary'
    | '/_app/carbon-mgmt/scope2-bill'
    | '/_app/carbon-mgmt/scope3-transport'
    | '/_app/carbon-mgmt/scope3-waste'
    | '/_app/carbon/hwpm'
    | '/_app/carbon/map'
    | '/_app/carbon/page2'
    | '/_app/carbon/page3'
    | '/_app/carbon/page4'
    | '/_app/data/alarm-events'
    | '/_app/data/alarm-rules'
    | '/_app/data/api-key-mapping'
    | '/_app/data/commute'
    | '/_app/data/company'
    | '/_app/data/energy-storage'
    | '/_app/data/inbound'
    | '/_app/data/meter'
    | '/_app/data/monitor-area'
    | '/_app/data/outbound'
    | '/_app/data/terminals'
    | '/_app/data/video'
    | '/_app/data/video-alarm-events'
    | '/_app/tasks/crontab'
    | '/_app/tasks/interval'
    | '/_app/tasks/schedules'
    | '/_app/teams/$teamId'
    | '/_app/teams/new'
    | '/_app/admin/'
    | '/_app/carbon/'
    | '/_app/profile/'
    | '/_app/teams/'
    | '/_app/admin/teams/$teamId'
    | '/_app/admin/users/$userId'
    | '/_public/auth/github/callback'
    | '/_public/auth/google/callback'
    | '/_app/admin/teams/'
    | '/_app/admin/users/'
    | '/_app/teams/$teamId/invitations/$invitationId/accept'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AppRoute: typeof AppRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/verify-email': {
      id: '/_public/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof PublicVerifyEmailRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/terms': {
      id: '/_public/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof PublicTermsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/signup': {
      id: '/_public/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof PublicSignupRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/reset-password': {
      id: '/_public/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof PublicResetPasswordRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/privacy': {
      id: '/_public/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PublicPrivacyRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/mfa-challenge': {
      id: '/_public/mfa-challenge'
      path: '/mfa-challenge'
      fullPath: '/mfa-challenge'
      preLoaderRoute: typeof PublicMfaChallengeRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/forgot-password': {
      id: '/_public/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof PublicForgotPasswordRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/about': {
      id: '/_public/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof PublicAboutRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_app/teams': {
      id: '/_app/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof AppTeamsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/platform': {
      id: '/_app/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof AppPlatformRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/home': {
      id: '/_app/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/carbon': {
      id: '/_app/carbon'
      path: '/carbon'
      fullPath: '/carbon'
      preLoaderRoute: typeof AppCarbonRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/teams/': {
      id: '/_app/teams/'
      path: '/'
      fullPath: '/teams/'
      preLoaderRoute: typeof AppTeamsIndexRouteImport
      parentRoute: typeof AppTeamsRoute
    }
    '/_app/profile/': {
      id: '/_app/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof AppProfileIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/carbon/': {
      id: '/_app/carbon/'
      path: '/'
      fullPath: '/carbon/'
      preLoaderRoute: typeof AppCarbonIndexRouteImport
      parentRoute: typeof AppCarbonRoute
    }
    '/_app/admin/': {
      id: '/_app/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/teams/new': {
      id: '/_app/teams/new'
      path: '/new'
      fullPath: '/teams/new'
      preLoaderRoute: typeof AppTeamsNewRouteImport
      parentRoute: typeof AppTeamsRoute
    }
    '/_app/teams/$teamId': {
      id: '/_app/teams/$teamId'
      path: '/$teamId'
      fullPath: '/teams/$teamId'
      preLoaderRoute: typeof AppTeamsTeamIdRouteImport
      parentRoute: typeof AppTeamsRoute
    }
    '/_app/tasks/schedules': {
      id: '/_app/tasks/schedules'
      path: '/tasks/schedules'
      fullPath: '/tasks/schedules'
      preLoaderRoute: typeof AppTasksSchedulesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tasks/interval': {
      id: '/_app/tasks/interval'
      path: '/tasks/interval'
      fullPath: '/tasks/interval'
      preLoaderRoute: typeof AppTasksIntervalRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tasks/crontab': {
      id: '/_app/tasks/crontab'
      path: '/tasks/crontab'
      fullPath: '/tasks/crontab'
      preLoaderRoute: typeof AppTasksCrontabRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/data/video-alarm-events': {
      id: '/_app/data/video-alarm-events'
      path: '/data/video-alarm-events'
      fullPath: '/data/video-alarm-events'
      preLoaderRoute: typeof AppDataVideoAlarmEventsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/data/video': {
      id: '/_app/data/video'
      path: '/data/video'
      fullPath: '/data/video'
      preLoaderRoute: typeof AppDataVideoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/data/terminals': {
      id: '/_app/data/terminals'
      path: '/data/terminals'
      fullPath: '/data/terminals'
      preLoaderRoute: typeof AppDataTerminalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/data/outbound': {
      id: '/_app/data/outbound'
      path: '/data/outbound'
      fullPath: '/data/outbound'
      preLoaderRoute: typeof AppDataOutboundRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/data/monitor-area': {
      id: '/_app/data/monitor-area'
      path: '/data/monitor-area'
      fullPath: '/data/monitor-area'
      preLoaderRoute: typeof AppDataMonitorAreaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/data/meter': {
      id: '/_app/data/meter'
      path: '/data/meter'
      fullPath: '/data/meter'
      preLoaderRoute: typeof AppDataMeterRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/data/inbound': {
      id: '/_app/data/inbound'
      path: '/data/inbound'
      fullPath: '/data/inbound'
      preLoaderRoute: typeof AppDataInboundRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/data/energy-storage': {
      id: '/_app/data/energy-storage'
      path: '/data/energy-storage'
      fullPath: '/data/energy-storage'
      preLoaderRoute: typeof AppDataEnergyStorageRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/data/company': {
      id: '/_app/data/company'
      path: '/data/company'
      fullPath: '/data/company'
      preLoaderRoute: typeof AppDataCompanyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/data/commute': {
      id: '/_app/data/commute'
      path: '/data/commute'
      fullPath: '/data/commute'
      preLoaderRoute: typeof AppDataCommuteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/data/api-key-mapping': {
      id: '/_app/data/api-key-mapping'
      path: '/data/api-key-mapping'
      fullPath: '/data/api-key-mapping'
      preLoaderRoute: typeof AppDataApiKeyMappingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/data/alarm-rules': {
      id: '/_app/data/alarm-rules'
      path: '/data/alarm-rules'
      fullPath: '/data/alarm-rules'
      preLoaderRoute: typeof AppDataAlarmRulesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/data/alarm-events': {
      id: '/_app/data/alarm-events'
      path: '/data/alarm-events'
      fullPath: '/data/alarm-events'
      preLoaderRoute: typeof AppDataAlarmEventsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/carbon/page4': {
      id: '/_app/carbon/page4'
      path: '/page4'
      fullPath: '/carbon/page4'
      preLoaderRoute: typeof AppCarbonPage4RouteImport
      parentRoute: typeof AppCarbonRoute
    }
    '/_app/carbon/page3': {
      id: '/_app/carbon/page3'
      path: '/page3'
      fullPath: '/carbon/page3'
      preLoaderRoute: typeof AppCarbonPage3RouteImport
      parentRoute: typeof AppCarbonRoute
    }
    '/_app/carbon/page2': {
      id: '/_app/carbon/page2'
      path: '/page2'
      fullPath: '/carbon/page2'
      preLoaderRoute: typeof AppCarbonPage2RouteImport
      parentRoute: typeof AppCarbonRoute
    }
    '/_app/carbon/map': {
      id: '/_app/carbon/map'
      path: '/map'
      fullPath: '/carbon/map'
      preLoaderRoute: typeof AppCarbonMapRouteImport
      parentRoute: typeof AppCarbonRoute
    }
    '/_app/carbon/hwpm': {
      id: '/_app/carbon/hwpm'
      path: '/hwpm'
      fullPath: '/carbon/hwpm'
      preLoaderRoute: typeof AppCarbonHwpmRouteImport
      parentRoute: typeof AppCarbonRoute
    }
    '/_app/carbon-mgmt/scope3-waste': {
      id: '/_app/carbon-mgmt/scope3-waste'
      path: '/carbon-mgmt/scope3-waste'
      fullPath: '/carbon-mgmt/scope3-waste'
      preLoaderRoute: typeof AppCarbonMgmtScope3WasteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/carbon-mgmt/scope3-transport': {
      id: '/_app/carbon-mgmt/scope3-transport'
      path: '/carbon-mgmt/scope3-transport'
      fullPath: '/carbon-mgmt/scope3-transport'
      preLoaderRoute: typeof AppCarbonMgmtScope3TransportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/carbon-mgmt/scope2-bill': {
      id: '/_app/carbon-mgmt/scope2-bill'
      path: '/carbon-mgmt/scope2-bill'
      fullPath: '/carbon-mgmt/scope2-bill'
      preLoaderRoute: typeof AppCarbonMgmtScope2BillRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/carbon-mgmt/scope1-stationary': {
      id: '/_app/carbon-mgmt/scope1-stationary'
      path: '/carbon-mgmt/scope1-stationary'
      fullPath: '/carbon-mgmt/scope1-stationary'
      preLoaderRoute: typeof AppCarbonMgmtScope1StationaryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/carbon-mgmt/scope1-refrigerant': {
      id: '/_app/carbon-mgmt/scope1-refrigerant'
      path: '/carbon-mgmt/scope1-refrigerant'
      fullPath: '/carbon-mgmt/scope1-refrigerant'
      preLoaderRoute: typeof AppCarbonMgmtScope1RefrigerantRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/carbon-mgmt/scope1-mobile': {
      id: '/_app/carbon-mgmt/scope1-mobile'
      path: '/carbon-mgmt/scope1-mobile'
      fullPath: '/carbon-mgmt/scope1-mobile'
      preLoaderRoute: typeof AppCarbonMgmtScope1MobileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/carbon-mgmt/iot': {
      id: '/_app/carbon-mgmt/iot'
      path: '/carbon-mgmt/iot'
      fullPath: '/carbon-mgmt/iot'
      preLoaderRoute: typeof AppCarbonMgmtIotRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/carbon-mgmt/factors': {
      id: '/_app/carbon-mgmt/factors'
      path: '/carbon-mgmt/factors'
      fullPath: '/carbon-mgmt/factors'
      preLoaderRoute: typeof AppCarbonMgmtFactorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/carbon-mgmt/audit': {
      id: '/_app/carbon-mgmt/audit'
      path: '/carbon-mgmt/audit'
      fullPath: '/carbon-mgmt/audit'
      preLoaderRoute: typeof AppCarbonMgmtAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/auth/users': {
      id: '/_app/auth/users'
      path: '/auth/users'
      fullPath: '/auth/users'
      preLoaderRoute: typeof AppAuthUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/auth/roles': {
      id: '/_app/auth/roles'
      path: '/auth/roles'
      fullPath: '/auth/roles'
      preLoaderRoute: typeof AppAuthRolesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/audit': {
      id: '/_app/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AppAdminAuditRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/users/': {
      id: '/_app/admin/users/'
      path: '/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AppAdminUsersIndexRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/teams/': {
      id: '/_app/admin/teams/'
      path: '/teams'
      fullPath: '/admin/teams/'
      preLoaderRoute: typeof AppAdminTeamsIndexRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_public/auth/google/callback': {
      id: '/_public/auth/google/callback'
      path: '/auth/google/callback'
      fullPath: '/auth/google/callback'
      preLoaderRoute: typeof PublicAuthGoogleCallbackRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/auth/github/callback': {
      id: '/_public/auth/github/callback'
      path: '/auth/github/callback'
      fullPath: '/auth/github/callback'
      preLoaderRoute: typeof PublicAuthGithubCallbackRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_app/admin/users/$userId': {
      id: '/_app/admin/users/$userId'
      path: '/users/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AppAdminUsersUserIdRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/teams/$teamId': {
      id: '/_app/admin/teams/$teamId'
      path: '/teams/$teamId'
      fullPath: '/admin/teams/$teamId'
      preLoaderRoute: typeof AppAdminTeamsTeamIdRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/teams/$teamId/invitations/$invitationId/accept': {
      id: '/_app/teams/$teamId/invitations/$invitationId/accept'
      path: '/invitations/$invitationId/accept'
      fullPath: '/teams/$teamId/invitations/$invitationId/accept'
      preLoaderRoute: typeof AppTeamsTeamIdInvitationsInvitationIdAcceptRouteImport
      parentRoute: typeof AppTeamsTeamIdRoute
    }
  }
}

interface AppAdminRouteChildren {
  AppAdminAuditRoute: typeof AppAdminAuditRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
  AppAdminTeamsTeamIdRoute: typeof AppAdminTeamsTeamIdRoute
  AppAdminUsersUserIdRoute: typeof AppAdminUsersUserIdRoute
  AppAdminTeamsIndexRoute: typeof AppAdminTeamsIndexRoute
  AppAdminUsersIndexRoute: typeof AppAdminUsersIndexRoute
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminAuditRoute: AppAdminAuditRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
  AppAdminTeamsTeamIdRoute: AppAdminTeamsTeamIdRoute,
  AppAdminUsersUserIdRoute: AppAdminUsersUserIdRoute,
  AppAdminTeamsIndexRoute: AppAdminTeamsIndexRoute,
  AppAdminUsersIndexRoute: AppAdminUsersIndexRoute,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppCarbonRouteChildren {
  AppCarbonHwpmRoute: typeof AppCarbonHwpmRoute
  AppCarbonMapRoute: typeof AppCarbonMapRoute
  AppCarbonPage2Route: typeof AppCarbonPage2Route
  AppCarbonPage3Route: typeof AppCarbonPage3Route
  AppCarbonPage4Route: typeof AppCarbonPage4Route
  AppCarbonIndexRoute: typeof AppCarbonIndexRoute
}

const AppCarbonRouteChildren: AppCarbonRouteChildren = {
  AppCarbonHwpmRoute: AppCarbonHwpmRoute,
  AppCarbonMapRoute: AppCarbonMapRoute,
  AppCarbonPage2Route: AppCarbonPage2Route,
  AppCarbonPage3Route: AppCarbonPage3Route,
  AppCarbonPage4Route: AppCarbonPage4Route,
  AppCarbonIndexRoute: AppCarbonIndexRoute,
}

const AppCarbonRouteWithChildren = AppCarbonRoute._addFileChildren(
  AppCarbonRouteChildren,
)

interface AppTeamsTeamIdRouteChildren {
  AppTeamsTeamIdInvitationsInvitationIdAcceptRoute: typeof AppTeamsTeamIdInvitationsInvitationIdAcceptRoute
}

const AppTeamsTeamIdRouteChildren: AppTeamsTeamIdRouteChildren = {
  AppTeamsTeamIdInvitationsInvitationIdAcceptRoute:
    AppTeamsTeamIdInvitationsInvitationIdAcceptRoute,
}

const AppTeamsTeamIdRouteWithChildren = AppTeamsTeamIdRoute._addFileChildren(
  AppTeamsTeamIdRouteChildren,
)

interface AppTeamsRouteChildren {
  AppTeamsTeamIdRoute: typeof AppTeamsTeamIdRouteWithChildren
  AppTeamsNewRoute: typeof AppTeamsNewRoute
  AppTeamsIndexRoute: typeof AppTeamsIndexRoute
}

const AppTeamsRouteChildren: AppTeamsRouteChildren = {
  AppTeamsTeamIdRoute: AppTeamsTeamIdRouteWithChildren,
  AppTeamsNewRoute: AppTeamsNewRoute,
  AppTeamsIndexRoute: AppTeamsIndexRoute,
}

const AppTeamsRouteWithChildren = AppTeamsRoute._addFileChildren(
  AppTeamsRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppCarbonRoute: typeof AppCarbonRouteWithChildren
  AppHomeRoute: typeof AppHomeRoute
  AppPlatformRoute: typeof AppPlatformRoute
  AppTeamsRoute: typeof AppTeamsRouteWithChildren
  AppAuthRolesRoute: typeof AppAuthRolesRoute
  AppAuthUsersRoute: typeof AppAuthUsersRoute
  AppCarbonMgmtAuditRoute: typeof AppCarbonMgmtAuditRoute
  AppCarbonMgmtFactorsRoute: typeof AppCarbonMgmtFactorsRoute
  AppCarbonMgmtIotRoute: typeof AppCarbonMgmtIotRoute
  AppCarbonMgmtScope1MobileRoute: typeof AppCarbonMgmtScope1MobileRoute
  AppCarbonMgmtScope1RefrigerantRoute: typeof AppCarbonMgmtScope1RefrigerantRoute
  AppCarbonMgmtScope1StationaryRoute: typeof AppCarbonMgmtScope1StationaryRoute
  AppCarbonMgmtScope2BillRoute: typeof AppCarbonMgmtScope2BillRoute
  AppCarbonMgmtScope3TransportRoute: typeof AppCarbonMgmtScope3TransportRoute
  AppCarbonMgmtScope3WasteRoute: typeof AppCarbonMgmtScope3WasteRoute
  AppDataAlarmEventsRoute: typeof AppDataAlarmEventsRoute
  AppDataAlarmRulesRoute: typeof AppDataAlarmRulesRoute
  AppDataApiKeyMappingRoute: typeof AppDataApiKeyMappingRoute
  AppDataCommuteRoute: typeof AppDataCommuteRoute
  AppDataCompanyRoute: typeof AppDataCompanyRoute
  AppDataEnergyStorageRoute: typeof AppDataEnergyStorageRoute
  AppDataInboundRoute: typeof AppDataInboundRoute
  AppDataMeterRoute: typeof AppDataMeterRoute
  AppDataMonitorAreaRoute: typeof AppDataMonitorAreaRoute
  AppDataOutboundRoute: typeof AppDataOutboundRoute
  AppDataTerminalsRoute: typeof AppDataTerminalsRoute
  AppDataVideoRoute: typeof AppDataVideoRoute
  AppDataVideoAlarmEventsRoute: typeof AppDataVideoAlarmEventsRoute
  AppTasksCrontabRoute: typeof AppTasksCrontabRoute
  AppTasksIntervalRoute: typeof AppTasksIntervalRoute
  AppTasksSchedulesRoute: typeof AppTasksSchedulesRoute
  AppProfileIndexRoute: typeof AppProfileIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRouteWithChildren,
  AppCarbonRoute: AppCarbonRouteWithChildren,
  AppHomeRoute: AppHomeRoute,
  AppPlatformRoute: AppPlatformRoute,
  AppTeamsRoute: AppTeamsRouteWithChildren,
  AppAuthRolesRoute: AppAuthRolesRoute,
  AppAuthUsersRoute: AppAuthUsersRoute,
  AppCarbonMgmtAuditRoute: AppCarbonMgmtAuditRoute,
  AppCarbonMgmtFactorsRoute: AppCarbonMgmtFactorsRoute,
  AppCarbonMgmtIotRoute: AppCarbonMgmtIotRoute,
  AppCarbonMgmtScope1MobileRoute: AppCarbonMgmtScope1MobileRoute,
  AppCarbonMgmtScope1RefrigerantRoute: AppCarbonMgmtScope1RefrigerantRoute,
  AppCarbonMgmtScope1StationaryRoute: AppCarbonMgmtScope1StationaryRoute,
  AppCarbonMgmtScope2BillRoute: AppCarbonMgmtScope2BillRoute,
  AppCarbonMgmtScope3TransportRoute: AppCarbonMgmtScope3TransportRoute,
  AppCarbonMgmtScope3WasteRoute: AppCarbonMgmtScope3WasteRoute,
  AppDataAlarmEventsRoute: AppDataAlarmEventsRoute,
  AppDataAlarmRulesRoute: AppDataAlarmRulesRoute,
  AppDataApiKeyMappingRoute: AppDataApiKeyMappingRoute,
  AppDataCommuteRoute: AppDataCommuteRoute,
  AppDataCompanyRoute: AppDataCompanyRoute,
  AppDataEnergyStorageRoute: AppDataEnergyStorageRoute,
  AppDataInboundRoute: AppDataInboundRoute,
  AppDataMeterRoute: AppDataMeterRoute,
  AppDataMonitorAreaRoute: AppDataMonitorAreaRoute,
  AppDataOutboundRoute: AppDataOutboundRoute,
  AppDataTerminalsRoute: AppDataTerminalsRoute,
  AppDataVideoRoute: AppDataVideoRoute,
  AppDataVideoAlarmEventsRoute: AppDataVideoAlarmEventsRoute,
  AppTasksCrontabRoute: AppTasksCrontabRoute,
  AppTasksIntervalRoute: AppTasksIntervalRoute,
  AppTasksSchedulesRoute: AppTasksSchedulesRoute,
  AppProfileIndexRoute: AppProfileIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface PublicRouteChildren {
  PublicAboutRoute: typeof PublicAboutRoute
  PublicForgotPasswordRoute: typeof PublicForgotPasswordRoute
  PublicLoginRoute: typeof PublicLoginRoute
  PublicMfaChallengeRoute: typeof PublicMfaChallengeRoute
  PublicPrivacyRoute: typeof PublicPrivacyRoute
  PublicResetPasswordRoute: typeof PublicResetPasswordRoute
  PublicSignupRoute: typeof PublicSignupRoute
  PublicTermsRoute: typeof PublicTermsRoute
  PublicVerifyEmailRoute: typeof PublicVerifyEmailRoute
  PublicAuthGithubCallbackRoute: typeof PublicAuthGithubCallbackRoute
  PublicAuthGoogleCallbackRoute: typeof PublicAuthGoogleCallbackRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicAboutRoute: PublicAboutRoute,
  PublicForgotPasswordRoute: PublicForgotPasswordRoute,
  PublicLoginRoute: PublicLoginRoute,
  PublicMfaChallengeRoute: PublicMfaChallengeRoute,
  PublicPrivacyRoute: PublicPrivacyRoute,
  PublicResetPasswordRoute: PublicResetPasswordRoute,
  PublicSignupRoute: PublicSignupRoute,
  PublicTermsRoute: PublicTermsRoute,
  PublicVerifyEmailRoute: PublicVerifyEmailRoute,
  PublicAuthGithubCallbackRoute: PublicAuthGithubCallbackRoute,
  PublicAuthGoogleCallbackRoute: PublicAuthGoogleCallbackRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AppRoute: AppRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
